version: '2'
services:
    nginx:
        image: tutum/nginx
        restart: always
        ports:
            - 80:80
        links:
            - phpfpm
            - db
        volumes:
            - ./nginx/default:/etc/nginx/sites-available/default
            - ./nginx/default:/etc/nginx/sites-enabled/default
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./html:/var/html
    phpfpm:
        build: ./php/.
        restart: always
        links:
            - mail
            - db
        ports:
            - 9000:9000
        links:
            - db
        volumes:
            - ./html:/var/html
    db:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: markdepro
        volumes:
            - ./mariadb:/var/lib/mysql
    mail:
        image: djfarrelly/maildev
        restart: always
        ports:
            - 82:80
            - 1025:25
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 81:80
        environment:
            PMA_ARBITRARY: 0
